export const FETCH_ITEMS = "FETCH_ITEMS";
export const FETCH_ALL = "FETCH_ALL";
export const FETCH_ACCESSORIES = "FETCH_ACCESSORIES";
export const FETCH_PLANTS = "FETCH_PLANTS";
export const FETCH_TOYS = "FETCH_TOYS";
export const FETCH_ITEMS_BY_CATEGORY = "FETCH_ITEMS_BY_CATEGORY";
export const UPDATE_CATEGORY = "UPADTE_CATEGORY";
