export const FETCH_DATA = "FETCH_DATA";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_BY_RELEASEDATE = "FETCH_BY_RELEASEDATE";
export const FETCH_BY_RANK = "FETCH_BY_RANK";
export const MODAL_IMAGE = "MODAL_IMAGE";
